import { ArrowLeft, BarChart3, Sparkles, TrendingDown, TrendingUp } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { request } from '@/lib/api'

type Trend = { interviewId: string; interviewTitle: string; scheduledAt: string; totalScore: number; professionalScore: number; expressionScore: number; logicScore: number; adaptabilityScore: number }
type Changes = { totalScore: number; professionalScore: number; expressionScore: number; logicScore: number; adaptabilityScore: number }
type Summary = { reportCount: number; latest?: Trend; previous?: Trend; changeFromPrevious: Changes; trends: Trend[] }
const labels: Array<[keyof Changes, string]> = [['professionalScore', '专业能力'], ['expressionScore', '表达能力'], ['logicScore', '逻辑思维'], ['adaptabilityScore', '应变能力']]
const day = (value: string) => value?.replace('T', ' ').slice(0, 10) || '-'
const change = (value: number) => `${value > 0 ? '+' : ''}${Number(value || 0).toFixed(1)}`

export function AbilityDashboard() {
  const navigate = useNavigate(); const [data, setData] = useState<Summary>(); const [error, setError] = useState('')
  useEffect(() => { void request<Summary>('/v1/reports/my/summary').then(setData).catch(reason => setError(reason instanceof Error ? reason.message : '无法获取能力数据')) }, [])
  const changes = data?.changeFromPrevious ?? { totalScore: 0, professionalScore: 0, expressionScore: 0, logicScore: 0, adaptabilityScore: 0 }
  const max = useMemo(() => Math.max(...(data?.trends.map(item => item.totalScore) ?? [100]), 100), [data])
  if (!data?.latest) return <div className="mx-auto max-w-xl py-20 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-emerald-50 text-emerald-600"><Sparkles /></span><h1 className="mt-5 text-2xl font-bold">你的能力曲线，从第一场开始</h1><p className="mt-3 text-sm text-muted-foreground">{error || '完成一次面试并生成报告后，这里将展示能力变化。'}</p><Button className="mt-6" onClick={() => navigate('/candidate/interviews')}>开始模拟面试</Button></div>
  return <div className="mx-auto max-w-6xl space-y-6"><header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><button onClick={() => navigate('/candidate/interviews')} className="mb-2 flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" />返回面试大厅</button><p className="text-sm font-semibold text-emerald-600">ABILITY DASHBOARD</p><h1 className="mt-1 text-3xl font-bold">你的能力成长轨迹</h1><p className="mt-2 text-muted-foreground">基于 {data.reportCount} 场已评测面试的可视化总结。</p></div><Button variant="secondary"><BarChart3 className="h-4 w-4" />已评测 {data.reportCount} 场</Button></header><section className="grid gap-5 overflow-hidden rounded-[28px] bg-gradient-to-br from-emerald-700 to-teal-900 p-7 text-white md:grid-cols-[1fr_auto]"><div><p className="text-sm text-emerald-100">当前综合能力值</p><strong className="mt-2 block text-6xl tracking-tight">{data.latest.totalScore}</strong><p className="mt-4 text-sm text-emerald-50/80">最近一次：{data.latest.interviewTitle} · {day(data.latest.scheduledAt)}</p></div><div className="rounded-2xl border border-white/15 bg-white/10 px-7 py-5 text-center"><p className="text-sm text-emerald-100">较上一次</p><strong className={`mt-2 block text-3xl ${changes.totalScore >= 0 ? 'text-emerald-200' : 'text-rose-200'}`}>{change(changes.totalScore)}</strong><p className="mt-1 text-xs text-emerald-100">综合得分变化</p></div></section><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{labels.map(([key, label]) => { const value = changes[key]; return <Card key={key}><p className="text-sm text-muted-foreground">{label}</p><div className="mt-4 flex items-center justify-between"><strong className={value >= 0 ? 'text-2xl text-emerald-600' : 'text-2xl text-rose-600'}>{change(value)}</strong>{value >= 0 ? <TrendingUp className="h-5 w-5 text-emerald-500" /> : <TrendingDown className="h-5 w-5 text-rose-500" />}</div><p className="mt-3 text-xs text-muted-foreground">相较上一份报告</p></Card> })}</div><Card><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-emerald-600">HISTORICAL TREND</p><h2 className="mt-1 text-xl font-bold">历史综合能力变化</h2></div><span className="text-sm text-muted-foreground">按面试时间排序</span></div><div className="mt-10 flex h-64 min-w-max items-end gap-4 border-b border-border px-3">{data.trends.map((item, index) => <div key={item.interviewId} className="flex w-16 flex-1 flex-col items-center gap-3"><div className="relative flex h-48 w-full items-end"><span className="absolute -top-6 w-full text-center text-xs font-bold">{item.totalScore}</span><div className="w-full rounded-t-xl bg-gradient-to-t from-emerald-700 to-teal-300 transition hover:from-emerald-600" style={{ height: `${Math.max(10, (item.totalScore / max) * 100)}%` }} /></div><strong className="text-xs">第 {index + 1} 次</strong><span className="whitespace-nowrap text-[10px] text-muted-foreground">{day(item.scheduledAt)}</span></div>)}</div></Card></div>
}
