import { BookOpen, BriefcaseBusiness, Play, Sparkles } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { CandidatePageShell } from '@/components/candidate-page-shell'
import { request, type Interview, type PracticeBank } from '@/lib/api'
export function CandidateLibrary(){const nav=useNavigate();const [banks,setBanks]=useState<PracticeBank[]>([]);const [busy,setBusy]=useState('');const [error,setError]=useState('');useEffect(()=>{void request<PracticeBank[]>('/v1/interviews/practice/banks').then(setBanks).catch(e=>setError(e.message))},[]);async function start(bank:PracticeBank){setBusy(bank.id);try{const interview=await request<Interview>('/v1/interviews/practice',{method:'POST',body:JSON.stringify({questionBankId:bank.id,questionCount:5,duration:30})});nav(`/candidate/interviews/${interview.id}/room`)}catch(e){setError(e instanceof Error?e.message:'无法创建练习')}finally{setBusy('')}}return <CandidatePageShell><div className="space-y-6"><header><p className="text-sm font-semibold text-[var(--accent)]">PRACTICE LIBRARY</p><h1 className="mt-2 text-3xl font-bold">题库与职业方向</h1><p className="mt-2 text-muted-foreground">选择题库，围绕目标岗位开展针对性 AI 模拟练习。</p></header>{error&&<p className="rounded-2xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</p>}<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{banks.map((bank,index)=><Card key={bank.id} className="flex min-h-64 flex-col"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[var(--accent-soft)] text-[var(--accent)]"><BookOpen className="h-5 w-5"/></span><Badge tone="info">{bank.questionCount} 题</Badge></div><p className="mt-6 text-xs font-semibold text-[var(--accent)]">LEARNING PATH {String(index+1).padStart(2,'0')}</p><h2 className="mt-2 text-xl font-bold">{bank.name}</h2><p className="mt-3 flex-1 text-sm leading-6 text-muted-foreground">{bank.description||'通过 AI 追问与即时反馈，强化这一方向的核心能力。'}</p><Button className="mt-6 w-full" disabled={busy===bank.id} onClick={()=>void start(bank)}>{busy===bank.id?'创建中…':'开始 30 分钟练习'}<Play className="h-4 w-4"/></Button></Card>)}</div><Card className="bg-gradient-to-br from-[var(--primary)] to-[var(--accent)] text-white"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="text-sm font-semibold text-white/80">CAREER FOCUS</p><h2 className="mt-2 text-2xl font-bold">还没有目标岗位？从通用能力开始。</h2><p className="mt-2 text-sm text-white/80/75">先完成一场基础模拟，再通过报告识别最值得投入的方向。</p></div><Button className="bg-white text-[var(--foreground)] hover:bg-[var(--accent-soft)]" onClick={()=>nav('/candidate/interviews')}><Sparkles className="h-4 w-4"/>查看我的面试</Button></div></Card></div></CandidatePageShell>}
